//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
== Use-Case: Benutzerkonto anlegen
===	Kurzbeschreibung
Privatkunden können ein Benutzerkonto anlegen, das ihm erlaubt, Bestellungen aufzugeben und den Stand von aufgebenen Bestellungen einzusehen. 

===	Kurzbeschreibung der Akteure
==== Privatkunde
Ein Privatkunde nutzt das System, um Bestellungen aufzugeben.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...
==== Besuchen der Website
Der Kunde verfügt über eine gültige E-Mail-Adresse und befindet sich auf der Website des Cocktailversands.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Kunde die Schaltfläche "Registrieren" betätigt
. Der Kunde gibt seine E-Mail sein Geburtsdatum und ein Passwort sowie die Bestätigung von diesem an. Er stimmt den Nutzungsbedingungen über eine Checkbox zu.
. Der Kunde betätigt die Registrierung über eine Schaltfläche.
. In seinem E-Mail-Postfach klickt er auf den Bestätigungslink aus der Mail, die er vom Cocktail-Versand erhalten hat.
. Der Kunde kann eine Lieferadresse (Anrede, Name, Vorname, Straße, Hausnummer, PLZ, Ort, Adresszusatz) hinzufügen oder diesen Schritt überspringen.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf
==== Ungültige Eingabe
Wenn der Privatkunde im Schritt 2 des Standardablauf
a. eine ungültige E-Mail-Adresse eingibt
b. sein Geburtsdatum erschließen lässt, dass er jünger als 16 ist 
c. das eingebene Passwort und die Bestätigung nicht übereinstimmen
d. das Passwort die Sicherheitsbedingungen des Systems nicht erfüllt 
e. die Nutzungsbedingungen nicht bestätigt wurden
f. eine Eingabe fehlt
fordert das System ihn auf, gültige Eingaben zu tätigen. Je nach ungültiger Eingabe werden Hinweise ausgegeben, die beschreiben, wie eine gültige Eingabe zu tätigen ist.
. Der Kunde korrigiert seine Eingaben.
. Der Use Case wird im Schritt 3 fortgesetzt.

==== Der Kunde ist jünger als 16
Wenn der Kunde im Schritt 2 des Standardablauf ein korrektes Geburtsdatum angibt, das erschließen lässt, dass er jünger als 16 ist, wird der Hinweis ausgegeben, dass ein Nutzer zum Anlegen eines Kundenkontos mind. 16 Jahre alt sein muss.
Fall 1:
. Der Use Case wird abgebrochen
Fall 2: 
. Der Nutzer gibt ein falsches Geburtsdatum an.
. Der Use Case wird im Schritt 3 fortgesetzt.

==== Der Kunde erhält keine Mail zur Bestätigung
Wenn der Kunde im Schritt 2 des Standardablauf eine falsche E-Mail-Adresse eingibt, bekommt er keine E-Mail zum Bestätigen seines Kontos.
. Der Kunde realisiert, dass er die falsche E-Mail-Adresse angegeben hat und versucht, sich erneut zu registrieren.
. Der Use Case wird im Schritt 1 fortgesetzt.

===	Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
==== Das Benutzerkonto wurde in der Datenbank gespeichert
E-Mail-Adresse, Geburtsdatum und das gehashte Passwort befinden sich in der Datenbank des Systems.
