//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
== Use-Case: Einsehen und Bestätigungen neuer Bestellungen
===	Kurzbeschreibung
//<Kurze Beschreibung des Use Case>
Die bestellten Waren können eingesehen und das abgeschlossene Bearbeiten einer Bestellung bestätigt werden.

===	Kurzbeschreibung der Akteure
==== Versandtabteilungsarbeiter
Der Versandtabteilungsarbeiter ist für die Zusammenstellung der Pakete verantwortlich.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...
. Der Versandtabteilungsarbeiter verfügt über ein Konto, das ihm Zugriff auf die Datenbank gewährt und ist hier eingeloggt. Er arbeitet über das Backend.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Versandtabteilungsarbeiter angibt, dass er die Bestellungen einsehen möchte.
. Ihm wird eine Liste mit Bestellungen angezeigt. Der Versandtabteilungsarbeiter gibt an, dass er Details einer Bestellung ansehen möchte.
. Der Versandtabteilungsarbeiter stellt das Paket zusammen.
. Der Versandtabteilungsarbeiter bestätigt die Bestellung.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Verschwendete Zutaten
Wenn der Versandtabteilungsarbeiter im Schritt 3 des Standardablauf aus einem beliebigen Grund mehr Zutaten verbraucht, als vorgesehen ist, so muss er dies dem System mitteilen.
. Der Versandtabteilungsarbeiter trägt ein, welche Zutaten er verschwendet hat
. Der Use Case wird im Schritt 4 fortgesetzt.

===	Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
==== Speichern von Daten in der Datenbank
Der neue Lagerbestand und der Stand der Bestellung werden gespeichert.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
==== Automatische Verwaltung des Lagerbestands
Mit der Bestätigung einer Bestellung wird der Bestand der Zutaten automatisch verändert.

==== Anzeige der Bestellungen
In der Standardanzeige wird die Liste mit Bestellungen nach dem Alter sortiert (älteste Bestellungen werden als Erstes angezeigt). Bestellungen, für deren Anfertigung Zutaten fehlen, werden entsprechend markiert und können in der Liste ein- und ausgeblendet werden.
