//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
== Use-Case: Einsehen und Bestätigungen neuer Bestellungen
===	Kurzbeschreibung
//<Kurze Beschreibung des Use Case>
Die bestellten Waren können eingesehen und das abgeschlossene Bearbeiten einer Bestellung bestätigt werden.

===	Kurzbeschreibung der Akteure
==== Versandabteilungsarbeiter
Der Versandabteilungsarbeiter ist für die Zusammenstellung der Pakete verantwortlich.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...
. Der Versandtabteilungsarbeiter verfügt über ein Konto, das ihm Zugriff auf die Datenbank gewährt und ist hier eingeloggt. Er arbeitet über das Backend.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Versandtabteilungsarbeiter angibt, dass er die Bestellungen einsehen möchte.
. Ihm wird eine Liste mit Bestellungen angezeigt. Der Versandtabteilungsarbeiter gibt an, dass er Details einer Bestellung ansehen möchte.
. Der Versandabteilungsarbeiter teilt dem System mit, dass die Bestellung nun bearbeitet wird.
. Der Versandabteilungsarbeiter stellt das Paket zusammen.
. Der Versandabteilungsarbeiter bestätigt die Bestellung.
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Verschwendete Zutaten
Wenn im Schritt 4 des Standardablauf aus einem beliebigen Grund mehr Zutaten als vorgesehen verbraucht werden, so muss der Versandtabteilungsarbeiter dies dem System mitteilen.

. Der Versandtabteilungsarbeiter trägt ein, welche Zutaten in welcher Menge verschwendet wurden
. Der Use Case wird im Schritt 4 fortgesetzt.

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.
==== Der Versandabteilungsarbeiter K möchte eine Bestellung abfertigen. Er ist bereits in seinem Account eingeloggt.
. K gibt an, dass er die Bestellungen einsehen möchte.
. K sieht die oberste Bestellung ein, für die alle Zutaten verfügbar sind.
. Er trägt ein, dass die Bestellung nun bearbeitet wird.
. Er beauftragt den Barkeeper, Cocktails zu mixen. Nach einiger Zeit nimmt K die Ware vom Barkeeper entgegen.
. K stellt das Paket zusammen.
. K bestätigt die Bestellung im System.

===	Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
==== Speichern von Daten in der Datenbank
Der neue Lagerbestand und der Stand der Bestellung werden gespeichert.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
==== Automatische Verwaltung des Lagerbestands
Mit dem der Bearbeitung einer Bestellung wird der Bestand der Zutaten in der Datenbank automatisch reduziert.

==== Anzeige der Bestellungen
In der Standardanzeige wird die Liste mit Bestellungen nach dem Alter sortiert (älteste Bestellungen werden als Erstes angezeigt). Bestellungen, für deren Anfertigung Zutaten fehlen, werden entsprechend markiert und können in der Liste ein- und ausgeblendet werden.
